apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: docker.pkg.github.com/complexk8s/docker-kubernetes/client:latest
      ports:
        - containerPort: 3000
